package schema

// Autogenerated using https://transform.tools/json-to-go
type Node struct {
	ID string `json:"id"`
	OS struct {
		Hostname     string `json:"hostname"`
		Type         string `json:"type"`
		Distribution string `json:"distribution"`
		Hardware     string `json:"hardware"`
	} `json:"os"`
	Usage struct {
		CPU float64 `json:"cpu"`
		RAM float64 `json:"ram"`
	} `json:"usage"`
}

type NodeInfo struct {
	ID           string
	Hostname     string
	Type         string
	Distribution string
	Hardware     string
}

type NodeUsage struct {
	ID  string
	CPU float64
	RAM float64
}

func ToNode(info NodeInfo, usage NodeUsage) Node {
	n := Node{
		ID: info.ID,
	}

	n.OS.Distribution = info.Distribution
	n.OS.Hardware = info.Hardware
	n.OS.Hostname = info.Hostname
	n.OS.Type = info.Type

	n.Usage.CPU = usage.CPU
	n.Usage.RAM = usage.RAM

	return n
}
