package schema

// Autogenerated using https://transform.tools/json-to-go
type Node struct {
	ID       string `json:"id"`
	Hostname string `json:"hostname"`
	OS       struct {
		Type         string `json:"type"`
		Distribution string `json:"distribution"`
		Hardware     string `json:"hardware"`
	} `json:"os"`
	Usage struct {
		CPU float64 `json:"cpu"`
		RAM int     `json:"ram"`
	} `json:"usage"`
}
